# .NET Core SDK
FROM mcr.microsoft.com/dotnet/core/sdk:3.1.402-alpine3.12 AS build

# Copy Projects
COPY source/Customer/Api/Microservices.Customer.Api.csproj ./Customer/Api/
COPY source/Customer/Application/Microservices.Customer.Application.csproj ./Customer/Application/
COPY source/Customer/Database/Microservices.Customer.Database.csproj ./Customer/Database/
COPY source/Customer/Domain/Microservices.Customer.Domain.csproj ./Customer/Domain/
COPY source/Customer/Model/Microservices.Customer.Model.csproj ./Customer/Model/
COPY source/Shared/Domain/Microservices.Shared.Domain.csproj ./Shared/Domain/

# .NET Core Restore
RUN dotnet restore ./Customer/Api/Microservices.Customer.Api.csproj

# Copy All Files
COPY source/Customer ./Customer/
COPY source/Shared ./Shared/

# .NET Core Publish
RUN dotnet publish ./Customer/Api/Microservices.Customer.Api.csproj -c Release -o /Customer/Dist

# ASP.NET Core
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1.8-alpine3.12
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
WORKDIR /App
COPY --from=build /Customer/Dist .
EXPOSE 443
ENTRYPOINT ["dotnet", "Microservices.Customer.Api.dll"]
